# Generated by Django 4.1.7 on 2023-03-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_time", models.TimeField(auto_created=True)),
                ("generated_date", models.DateField(auto_created=True)),
                ("title", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published_date", models.DateField(auto_created=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_published",
                    models.BooleanField(default=True, help_text="Is book published."),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="notifications.author",
                    ),
                ),
            ],
        ),
    ]
