# Generated by Django 4.1.7 on 2023-03-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_generated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="generated_date",
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="generated_time",
            field=models.TimeField(auto_created=True, blank=True, null=True),
        ),
    ]
